### ISSUE TITLE
Installation get's stuck

### ISSUE THREAD

**Issue by Naaf3** [danielfett/bluebattery.py#12]
Hi,

I'm trying to install the BlueBattery script on my Debian 11 Supervised Home Assistant machine, but it allways get's stuck at this point:

Stored in directory: /tmp/pip-ephem-wheel-cache-zgggum20/wheels/77/ad/dd/5e14061c923fdfcc32a69db5f859ec2b912886871e4a01cb84
  Building wheel for dbus-fast (PEP 517) ... /

This happens with both types of installation.

Some weeks ago on another machine, the installation worked without any problems.

Regards
Basti

**Comment by danielfett** [comment]
How long did you wait?

**Comment by Naaf3** [comment]
I waited about 30 minutes.

**Comment by Naaf3** [comment]
Is there any chance, that the installation will work again? Or any ideas what is going wrong on my system?

**Comment by Naaf3** [comment]
It worked. Tried it with another image :-)
